services:
  - type: web
    name: pet-shop-backend
    runtime: node
    plan: free
    rootDir: Pet-Shop-Backend
    buildCommand: npm install
    startCommand: node index.js
    healthCheckPath: /categories/all
